apiVersion: v1
kind: Service
metadata:
  name: users-service # Ou farm-service no outro repositório
spec:
  type: LoadBalancer # Crucial para gerar um IP público no Azure AKS [cite: 31, 55]
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app:  users # Altere para 'app: farm' no repositório de propriedades